plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\HARRY\\Smilehub\\smilehub-ecommerce\\frontend"
publishOrigin = "default"
base = "C:\\Users\\HARRY\\Smilehub\\smilehub-ecommerce\\frontend"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]